# Generated by Django 5.2 on 2025-04-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('url_api', models.URLField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_ofertas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('exito', 'Éxito'), ('fallido', 'Fallido')], max_length=20)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Integracion_datos.fuentedatos')),
            ],
        ),
    ]
