# Generated by Django 5.2 on 2025-04-16 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='habilidades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Lista de habilidades como: electricista, Baja Tensión, mantenimiento eléctrico', size=None),
        ),
    ]
